name       : python-chardet
version    : 2.3.0
release    : 1
source     :
    - https://pypi.python.org/packages/source/c/chardet/chardet-2.3.0.tar.gz : e53e38b3a4afe6d1132de62b7400a4ac363452dc5dfcf8d88e8e0cce663c68aa
license    : LGPL-2.1
summary    : Python Chardet - The Universal Character Encoding Detector
description: |
    Python Chardet - The Universal Character Encoding Detector
builddeps  :
    - python-setuptools
setup      : |
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
