name       : python-chardet
version    : 4.0.0
release    : 11
source     :
    - https://github.com/chardet/chardet/archive/4.0.0.tar.gz : 67bbe3eb02691d38831ddf2719c40fe09381bc17f15321946f6cd71dc274e530
homepage   : https://github.com/chardet/chardet
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python character encoding detector
description: |
    Python Chardet - The Universal Character Encoding Detector
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
