name       : python-chardet
version    : 5.0.0
release    : 12
source     :
    - https://github.com/chardet/chardet/archive/5.0.0.tar.gz : c301d48776767fb0cf6208125804450e1911e686a7954b3fe7b996c2d2ce570b
homepage   : https://github.com/chardet/chardet
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python character encoding detector
description: |
    Python Chardet - The Universal Character Encoding Detector
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
