name       : python-chardet
version    : 5.1.0
release    : 13
source     :
    - https://github.com/chardet/chardet/archive/5.1.0.tar.gz : 556325114dc086fb2aaaf8ca06efda4cb9eba417095d8689ddc560da97313dd9
homepage   : https://github.com/chardet/chardet
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python character encoding detector
description: |
    Python Chardet - The Universal Character Encoding Detector
builddeps  :
    - python-build
    - python-installer
    - python-pytest
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
