name       : python-chardet
version    : 3.0.4
release    : 5
source     :
    - https://github.com/chardet/chardet/archive/3.0.4.tar.gz : d5620025cfca430f6c2e28ddbc87c3c66a5c82fa65570ae975c92911c2190189
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python Chardet - The Universal Character Encoding Detector
description: |
    Python Chardet - The Universal Character Encoding Detector
builddeps  :
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "${_f}" "${_f}3"
    done
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        py.test
    popd

    pushd $PKG_BUILD_DIR/py3build
        py.test3
    popd
