name       : python-chardet
version    : 4.0.0
release    : 8
source     :
    - https://github.com/chardet/chardet/archive/4.0.0.tar.gz : 67bbe3eb02691d38831ddf2719c40fe09381bc17f15321946f6cd71dc274e530
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python Chardet - The Universal Character Encoding Detector
description: |
    Python Chardet - The Universal Character Encoding Detector
builddeps  :
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "${_f}" "${_f}3"
    done
    %python_install
#check      : |
#    %python3_test pytest3
